# Generated by Django 3.2.15 on 2022-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.TextField(unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
