# Generated by Django 3.2.15 on 2022-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0003_auto_20221002_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
