# Generated by Django 3.2.15 on 2022-10-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0007_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBRY_MNGMNT_SYTM_APP.book')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBRY_MNGMNT_SYTM_APP.members')),
            ],
        ),
    ]
