# Generated by Django 3.2.15 on 2022-10-05 10:53

import LIBRY_MNGMNT_SYTM_APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0008_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='expirydate',
            field=models.DateField(default=LIBRY_MNGMNT_SYTM_APP.models.expiry),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuedate',
            field=models.DateField(auto_now=True),
        ),
    ]
