# Generated by Django 3.2.15 on 2022-10-06 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LIBRY_MNGMNT_SYTM_APP', '0010_auto_20221005_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.CreateModel(
            name='spassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass1', models.CharField(max_length=255)),
                ('pass2', models.CharField(max_length=255)),
                ('pass3', models.CharField(max_length=255)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
