# Generated by Django 3.2.15 on 2022-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0011_auto_20221006_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spassword',
            name='usr',
            field=models.CharField(max_length=255),
        ),
    ]
