# Generated by Django 3.2.15 on 2022-10-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0012_alter_spassword_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.CharField(blank=True, max_length=255)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIBRY_MNGMNT_SYTM_APP.issue')),
            ],
        ),
        migrations.DeleteModel(
            name='spassword',
        ),
    ]
