# Generated by Django 3.2.15 on 2022-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0014_auto_20221010_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
