# Generated by Django 3.2.15 on 2022-10-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0015_issue_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
