# Generated by Django 3.2.15 on 2022-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0016_auto_20221012_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
