# Generated by Django 3.2.15 on 2022-10-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIBRY_MNGMNT_SYTM_APP', '0018_alter_members_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='penalty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
